### ISSUE TITLE
two questions about mp1

### ISSUE THREAD

**Issue by B04902039** [SystemProgrammingatNTU/SP16Issues#6]
Dear professor Shih and TAs:
Q1:
Where should we put our `Makefile` and `.cpp` files? Is under `/SP16MP1-StudentID/StudentID`  or  `/SP16MP1-StudentID`?

Q2:
How do we test our code on `/tmp2`?  Can we just make a dir call `/MystudentID`? Will other ppl able to access it that make my code seen?

Thank for your help.

**Comment by cchao** [comment]
1. Under the root directory of your repository. Please see the [sample judge script](https://systemprogrammingatntu.github.io/MP1/#how-we-may-test-your-program).

2. Please see [hints](https://systemprogrammingatntu.github.io/MP1/#hints)

```sh
mkdir /tmp2/YOUR_STUDENT_ID
chmod 700 /tmp2/YOUR_STUDENT_ID # Only you can access it
cd /tmp2/YOUR_STUDENT_ID
```

**Comment by B04902039** [comment]
Thanks!
